#!/usr/bin/env python3
"""Extract pure functions verbatim from the pinned npm CLI; never execute its main."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PACKAGE = ROOT / 'vendor/langwatch-1.18.0'
bundle = (PACKAGE / 'dist/cli/bundle.js').read_text()
parts = {
    'esbuild_helpers': bundle[bundle.index('"use strict";'):bundle.index('function lc(')],
    'rollout_parser': bundle[bundle.index('function Wie('):bundle.index('function Kc(')],
    'otlp_builder': bundle[bundle.index('function ese('):bundle.index('async function iW(')],
}
header = '''// LangWatch npm 1.18.0, package license MIT. Generated by extract-official.py.
// These upstream pure functions are verbatim. No CLI entrypoint or global setup runs.
// See upstream-source.json for provenance and hashes. Do not hand-edit the parser.
'''
output = header + '\n'.join(parts.values()) + '''
var oW = require('node:crypto');
rw();
module.exports = { parseRollout: ss, turnsToOtlp: tse };
'''
(ROOT / 'official-rollout.cjs').write_text(output)
(ROOT / 'upstream-source.json').write_text(json.dumps({
    'package': 'langwatch', 'version': '1.18.0', 'license': 'MIT',
    'url': 'https://registry.npmjs.org/langwatch/-/langwatch-1.18.0.tgz',
    'bundle_sha256': hashlib.sha256(bundle.encode()).hexdigest(),
    'extracted_sha256': hashlib.sha256(output.encode()).hexdigest(),
    'segments': {name: hashlib.sha256(value.encode()).hexdigest() for name, value in parts.items()},
    'adapter_difference': 'Only pure parser and OTLP builder are reused. No CLI installation, global config, login, daemon, historical scan, session-context spool or model gateway. Only the notified thread is read; the last three turns are submitted, with project correlation attributes added.',
}, indent=2) + '\n')
